### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by fabric-and-ink** [rust-lang-nursery/chalk#41]
- [x] Introduce a glossary at the root of the project with pointers to literature (#51) .

The following items are on hold until I learned more about logic and types. This thing is still like alien technology for me 😀 
- ~~"Massage-in" the essence of the wonderful blog posts by Niko and Aaron.~~
- ~~`#![warn(missing_docs)]`.~~

**Comment by aturon** [comment]
Hah, love it! All good things to do.

**Comment by tomwhoiscontrary** [comment]
It would be unimportant but nice to specify the desired pronunciation of the name. Is it the English word "chalk", or the Greek "χαλκ-", which, based on my rusty Ancient Greek, is more like "halk", rhyming with "talc"?

Also, Chalkidiki is a peninsula, rather than an island. Although it was temporarily and island after a [Persian megalomaniac dug a big trench across it](https://en.wikipedia.org/wiki/Xerxes_Canal).

**Comment by fabric-and-ink** [comment]
I plan to start a mdbook and will open a separate issue for that when I am ready.
